
package Vista;


public class DashboardSimple extends javax.swing.JFrame {

    //UIDashBoard uiBackoffice = new UIDashBoard();
    
    public DashboardSimple() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btAgregarUsr = new javax.swing.JButton();
        panelSuper = new Vista.PanelSuperUsuario();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Backoffice");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btAgregarUsr.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        btAgregarUsr.setText("Agregar Usuario");
        btAgregarUsr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgregarUsrActionPerformed(evt);
            }
        });
        getContentPane().add(btAgregarUsr, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 649, 880, 40));
        getContentPane().add(panelSuper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAgregarUsrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgregarUsrActionPerformed
        //uiBackoffice.RegistrarUsuario(this);
    }//GEN-LAST:event_btAgregarUsrActionPerformed

    public PanelSuperUsuario getPanelSuper() {
        return panelSuper;
    }

    public void setPanelSuper(PanelSuperUsuario panelSuper) {
        this.panelSuper = panelSuper;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardSimple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardSimple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardSimple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardSimple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardSimple().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAgregarUsr;
    private Vista.PanelSuperUsuario panelSuper;
    // End of variables declaration//GEN-END:variables
}
