/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Andrey
 */
public class PanelCoordinador extends javax.swing.JPanel {

    /**
     * Creates new form PanelCoordinador
     */
    public PanelCoordinador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGeneral1 = new Vista.PanelGeneral();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(panelGeneral1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1330, 730));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vista.PanelGeneral panelGeneral1;
    // End of variables declaration//GEN-END:variables
}
