/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JComboBox;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Andrey
 */
public class PanelSuperUsuario extends javax.swing.JPanel {

    /**
     * Creates new form PanelSuperUsuario
     */
    public PanelSuperUsuario() {
        initComponents();
    }

    public JTextField getTxtCorreo() {
        return txtCorreo;
    }

    public JTextField getTxtID() {
        return txtID;
    }

    public JTextField getTxtNombre() {
        return txtNombre;
    }

    public JPasswordField getTxtPassword() {
        return txtPassword;
    }

    public JPasswordField getTxtPasswordRp() {
        return txtPasswordRp;
    }

    public JTextField getTxtTelefono() {
        return txtTelefono;
    }

    public JTextField getTxtUsuario() {
        return txtUsuario;
    }

    public JComboBox<String> getCbRol() {
        return cbRol;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInfoUsuarioIC = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtPasswordRp = new javax.swing.JPasswordField();
        txtPassword = new javax.swing.JPasswordField();
        cbRol = new javax.swing.JComboBox<>();
        lblRol = new javax.swing.JLabel();
        lblContrasenhaRp = new javax.swing.JLabel();
        lblContrasenha = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblInfoUsuario = new javax.swing.JLabel();
        lblPerfilUsuario = new javax.swing.JLabel();
        lblDatosIcon = new javax.swing.JLabel();
        lblIcono = new javax.swing.JLabel();
        panelGeneral1 = new Vista.PanelGeneral();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInfoUsuarioIC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/usuarioIcon.jpg"))); // NOI18N
        add(lblInfoUsuarioIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, -1, -1));

        txtTelefono.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 580, 310, 30));

        txtID.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 510, 310, 30));

        txtCorreo.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, 310, 30));

        txtUsuario.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 370, 310, 30));

        txtNombre.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 310, 30));

        txtPasswordRp.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txtPasswordRp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordRpActionPerformed(evt);
            }
        });
        add(txtPasswordRp, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 510, 310, 30));

        txtPassword.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 440, 310, 30));

        cbRol.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        cbRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SuperUsuario", "Coordinador", "Asistente", "Dirección" }));
        cbRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRolActionPerformed(evt);
            }
        });
        add(cbRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 580, 310, 30));

        lblRol.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblRol.setText("Rol de Usuario:");
        add(lblRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 550, -1, -1));

        lblContrasenhaRp.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblContrasenhaRp.setText("Repetir Contraseña:");
        add(lblContrasenhaRp, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 480, -1, -1));

        lblContrasenha.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblContrasenha.setText("Contraseña:");
        add(lblContrasenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 410, -1, -1));

        lblUsuario.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblUsuario.setText("Usuario:");
        add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 340, -1, -1));

        lblTelefono.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblTelefono.setText("Teléfono:");
        add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 550, -1, 20));

        lblCorreo.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblCorreo.setText("Correo:");
        add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, -1, -1));

        lblID.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblID.setText("Identificación:");
        add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, -1, -1));

        lblTitulo.setFont(new java.awt.Font("Verdana", 1, 28)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(240, 0, 0));
        lblTitulo.setText("Asignar Roles de Autorización");
        add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, -1, -1));

        lblNombre.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblNombre.setText("Nombre:");
        add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, -1, 20));

        lblInfoUsuario.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        lblInfoUsuario.setText("Datos de Usuario");
        add(lblInfoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 280, -1, -1));

        lblPerfilUsuario.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        lblPerfilUsuario.setText("Datos de la Persona");
        add(lblPerfilUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, -1, -1));

        lblDatosIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/iconoDatosPersonales.PNG"))); // NOI18N
        add(lblDatosIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 270, -1, -1));

        lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/rolesIcono.png"))); // NOI18N
        add(lblIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, -1, -1));

        panelGeneral1.setBackground(new java.awt.Color(255, 255, 255));
        add(panelGeneral1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtPasswordRpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordRpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordRpActionPerformed

    private void cbRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbRolActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbRol;
    private javax.swing.JLabel lblContrasenha;
    private javax.swing.JLabel lblContrasenhaRp;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblDatosIcon;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblIcono;
    private javax.swing.JLabel lblInfoUsuario;
    private javax.swing.JLabel lblInfoUsuarioIC;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPerfilUsuario;
    private javax.swing.JLabel lblRol;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuario;
    private Vista.PanelGeneral panelGeneral1;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtPasswordRp;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
