/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Andrey
 */
public class PanelSolicitudes extends HerramientasBackoffice{

    /**
     * Creates new form PanelCoordinador
     */
    public PanelSolicitudes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        cbEstado = new javax.swing.JComboBox<>();
        lblFiltro = new javax.swing.JLabel();
        dpDesde = new org.jdesktop.swingx.JXDatePicker();
        dpHasta = new org.jdesktop.swingx.JXDatePicker();
        lblDesde = new javax.swing.JLabel();
        lblHasta = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabSolicitudes = new org.jdesktop.swingx.JXTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelFondo.setBackground(new java.awt.Color(255, 255, 255));
        panelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbEstado.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        cbEstado.setToolTipText("Filtrar las solicitudes por estado");
        cbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEstadoActionPerformed(evt);
            }
        });
        panelFondo.add(cbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 460, 159, -1));

        lblFiltro.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        lblFiltro.setText("Filtrar por estado:");
        panelFondo.add(lblFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, -1, -1));

        dpDesde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dpDesdeActionPerformed(evt);
            }
        });
        panelFondo.add(dpDesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        dpHasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dpHastaActionPerformed(evt);
            }
        });
        panelFondo.add(dpHasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, -1, -1));

        lblDesde.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        lblDesde.setText("Desde:");
        panelFondo.add(lblDesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 31, -1, -1));

        lblHasta.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        lblHasta.setText("Hasta:");
        panelFondo.add(lblHasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));

        tabSolicitudes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabSolicitudes);

        panelFondo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 64, 937, 378));

        add(panelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 530));
    }// </editor-fold>//GEN-END:initComponents

    private void cbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEstadoActionPerformed

    private void dpHastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dpHastaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dpHastaActionPerformed

    private void dpDesdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dpDesdeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dpDesdeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbEstado;
    private org.jdesktop.swingx.JXDatePicker dpDesde;
    private org.jdesktop.swingx.JXDatePicker dpHasta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDesde;
    private javax.swing.JLabel lblFiltro;
    private javax.swing.JLabel lblHasta;
    private javax.swing.JPanel panelFondo;
    private org.jdesktop.swingx.JXTable tabSolicitudes;
    // End of variables declaration//GEN-END:variables
}
