/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Andrey
 */
public class PanelGeneral extends javax.swing.JPanel {

    /**
     * Creates new form PanelSuperUsuario
     */
    public PanelGeneral() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIcono = new javax.swing.JLabel();
        lblHeader = new javax.swing.JLabel();
        lblBlanco = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/logo2.png"))); // NOI18N
        add(lblIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 330, 90));

        lblHeader.setBackground(new java.awt.Color(0, 0, 0));
        lblHeader.setOpaque(true);
        add(lblHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 110));

        lblBlanco.setBackground(new java.awt.Color(255, 255, 255));
        lblBlanco.setOpaque(true);
        add(lblBlanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1400, 730));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBlanco;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblIcono;
    // End of variables declaration//GEN-END:variables
}
